version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/page"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
