// GENERATED by tools/vulkan-bridge-generator/generate.py -- do not edit by hand.
// Regenerate with the `vulkan-bridge-generate` CMake target after changing the allowlist or vk.xml.
#pragma once

#include "vk_bridge_serial.hpp"

namespace sogen::gpu_bridge::marshal
{
    inline void encode(writer& w, const VkApplicationInfo& value);
    inline bool decode(reader& r, arena& a, VkApplicationInfo& value);
    inline void encode(writer& w, const VkInstanceCreateInfo& value);
    inline bool decode(reader& r, arena& a, VkInstanceCreateInfo& value);

    inline void encode(writer& w, const VkApplicationInfo& value)
    {
        w.scalar(value.sType);
        encode_pnext(w, value.pNext);
        encode_string(w, value.pApplicationName);
        w.scalar(value.applicationVersion);
        encode_string(w, value.pEngineName);
        w.scalar(value.engineVersion);
        w.scalar(value.apiVersion);
    }

    inline bool decode(reader& r, arena& a, VkApplicationInfo& value)
    {
        value = {};
        if (!r.scalar(value.sType)) { return false; }
        value.pNext = nullptr;
        if (!decode_pnext(r)) { return false; }
        value.pApplicationName = decode_string(r, a);
        if (!r.scalar(value.applicationVersion)) { return false; }
        value.pEngineName = decode_string(r, a);
        if (!r.scalar(value.engineVersion)) { return false; }
        if (!r.scalar(value.apiVersion)) { return false; }
        return true;
    }

    inline void encode(writer& w, const VkInstanceCreateInfo& value)
    {
        w.scalar(value.sType);
        encode_pnext(w, value.pNext);
        w.scalar(value.flags);
        if (value.pApplicationInfo)
        {
            w.flag(true);
            encode(w, *value.pApplicationInfo);
        }
        else
        {
            w.flag(false);
        }
        w.scalar(value.enabledLayerCount);
        encode_string_array(w, value.ppEnabledLayerNames, value.enabledLayerCount);
        w.scalar(value.enabledExtensionCount);
        encode_string_array(w, value.ppEnabledExtensionNames, value.enabledExtensionCount);
    }

    inline bool decode(reader& r, arena& a, VkInstanceCreateInfo& value)
    {
        value = {};
        if (!r.scalar(value.sType)) { return false; }
        value.pNext = nullptr;
        if (!decode_pnext(r)) { return false; }
        if (!r.scalar(value.flags)) { return false; }
        {
            bool present = false;
            if (!r.flag(present)) { return false; }
            if (present)
            {
                auto* pointee = a.allocate_array<VkApplicationInfo>(1);
                if (!decode(r, a, *pointee)) { return false; }
                value.pApplicationInfo = pointee;
            }
        }
        if (!r.scalar(value.enabledLayerCount)) { return false; }
        value.ppEnabledLayerNames = decode_string_array(r, a, value.enabledLayerCount);
        if (!r.scalar(value.enabledExtensionCount)) { return false; }
        value.ppEnabledExtensionNames = decode_string_array(r, a, value.enabledExtensionCount);
        return true;
    }
}
