// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class DebugCommandResponse implements flatbuffers.IUnpackableObject<DebugCommandResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DebugCommandResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDebugCommandResponse(bb:flatbuffers.ByteBuffer, obj?:DebugCommandResponse):DebugCommandResponse {
  return (obj || new DebugCommandResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDebugCommandResponse(bb:flatbuffers.ByteBuffer, obj?:DebugCommandResponse):DebugCommandResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DebugCommandResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

mutate_id(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeUint32(this.bb_pos + offset, value);
  return true;
}

ok():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

mutate_ok(value:boolean):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt8(this.bb_pos + offset, +value);
  return true;
}

payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startDebugCommandResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addOk(builder:flatbuffers.Builder, ok:boolean) {
  builder.addFieldInt8(1, +ok, +false);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endDebugCommandResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDebugCommandResponse(builder:flatbuffers.Builder, id:number, ok:boolean, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  DebugCommandResponse.startDebugCommandResponse(builder);
  DebugCommandResponse.addId(builder, id);
  DebugCommandResponse.addOk(builder, ok);
  DebugCommandResponse.addPayload(builder, payloadOffset);
  return DebugCommandResponse.endDebugCommandResponse(builder);
}

unpack(): DebugCommandResponseT {
  return new DebugCommandResponseT(
    this.id(),
    this.ok(),
    this.bb!.createScalarList<number>(this.payload.bind(this), this.payloadLength())
  );
}


unpackTo(_o: DebugCommandResponseT): void {
  _o.id = this.id();
  _o.ok = this.ok();
  _o.payload = this.bb!.createScalarList<number>(this.payload.bind(this), this.payloadLength());
}
}

export class DebugCommandResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public id: number = 0,
  public ok: boolean = false,
  public payload: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const payload = DebugCommandResponse.createPayloadVector(builder, this.payload);

  return DebugCommandResponse.createDebugCommandResponse(builder,
    this.id,
    this.ok,
    payload
  );
}
}
