// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class GetMemoryRegionsRequest implements flatbuffers.IUnpackableObject<GetMemoryRegionsRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetMemoryRegionsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetMemoryRegionsRequest(bb:flatbuffers.ByteBuffer, obj?:GetMemoryRegionsRequest):GetMemoryRegionsRequest {
  return (obj || new GetMemoryRegionsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetMemoryRegionsRequest(bb:flatbuffers.ByteBuffer, obj?:GetMemoryRegionsRequest):GetMemoryRegionsRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetMemoryRegionsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGetMemoryRegionsRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGetMemoryRegionsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetMemoryRegionsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetMemoryRegionsRequest.startGetMemoryRegionsRequest(builder);
  return GetMemoryRegionsRequest.endGetMemoryRegionsRequest(builder);
}

unpack(): GetMemoryRegionsRequestT {
  return new GetMemoryRegionsRequestT();
}


unpackTo(_o: GetMemoryRegionsRequestT): void {}
}

export class GetMemoryRegionsRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return GetMemoryRegionsRequest.createGetMemoryRegionsRequest(builder);
}
}
