// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class GetMemoryRegionsResponse implements flatbuffers.IUnpackableObject<GetMemoryRegionsResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetMemoryRegionsResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetMemoryRegionsResponse(bb:flatbuffers.ByteBuffer, obj?:GetMemoryRegionsResponse):GetMemoryRegionsResponse {
  return (obj || new GetMemoryRegionsResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetMemoryRegionsResponse(bb:flatbuffers.ByteBuffer, obj?:GetMemoryRegionsResponse):GetMemoryRegionsResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetMemoryRegionsResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regions(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

regionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

regionsArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startGetMemoryRegionsResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRegions(builder:flatbuffers.Builder, regionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionsOffset, 0);
}

static createRegionsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startRegionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endGetMemoryRegionsResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetMemoryRegionsResponse(builder:flatbuffers.Builder, regionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetMemoryRegionsResponse.startGetMemoryRegionsResponse(builder);
  GetMemoryRegionsResponse.addRegions(builder, regionsOffset);
  return GetMemoryRegionsResponse.endGetMemoryRegionsResponse(builder);
}

unpack(): GetMemoryRegionsResponseT {
  return new GetMemoryRegionsResponseT(
    this.bb!.createScalarList<number>(this.regions.bind(this), this.regionsLength())
  );
}


unpackTo(_o: GetMemoryRegionsResponseT): void {
  _o.regions = this.bb!.createScalarList<number>(this.regions.bind(this), this.regionsLength());
}
}

export class GetMemoryRegionsResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public regions: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const regions = GetMemoryRegionsResponse.createRegionsVector(builder, this.regions);

  return GetMemoryRegionsResponse.createGetMemoryRegionsResponse(builder,
    regions
  );
}
}
