// clang-format off
// Generated by src/tools/gen-bsd-syscall-table/gen_bsd_syscall_table.py. Do not edit.
// Source: apple-oss-distributions/xnu xnu-12377.121.6 osfmk/kern/syscall_sw.c
#include "mach_trap_table.hpp"

#include <array>

namespace sogen
{
    namespace
    {
        constexpr std::array<mach_trap_prototype, 101> traps{{
            {},
            {},
            {},
            {.name = "mach_absolute_time", .argument_count = 0},
            {.name = "mach_continuous_time", .argument_count = 0},
            {},
            {},
            {},
            {},
            {},
            {.name = "_kernelrpc_mach_vm_allocate_trap", .argument_count = 4},
            {.name = "_kernelrpc_mach_vm_purgable_control_trap", .argument_count = 4},
            {.name = "_kernelrpc_mach_vm_deallocate_trap", .argument_count = 3},
            {.name = "task_dyld_process_info_notify_get_trap", .argument_count = 2},
            {.name = "_kernelrpc_mach_vm_protect_trap", .argument_count = 5},
            {.name = "_kernelrpc_mach_vm_map_trap", .argument_count = 6},
            {.name = "_kernelrpc_mach_port_allocate_trap", .argument_count = 3},
            {},
            {.name = "_kernelrpc_mach_port_deallocate_trap", .argument_count = 2},
            {.name = "_kernelrpc_mach_port_mod_refs_trap", .argument_count = 4},
            {.name = "_kernelrpc_mach_port_move_member_trap", .argument_count = 3},
            {.name = "_kernelrpc_mach_port_insert_right_trap", .argument_count = 4},
            {.name = "_kernelrpc_mach_port_insert_member_trap", .argument_count = 3},
            {.name = "_kernelrpc_mach_port_extract_member_trap", .argument_count = 3},
            {.name = "_kernelrpc_mach_port_construct_trap", .argument_count = 4},
            {.name = "_kernelrpc_mach_port_destruct_trap", .argument_count = 4},
            {.name = "mach_reply_port", .argument_count = 0},
            {.name = "thread_self_trap", .argument_count = 0},
            {.name = "task_self_trap", .argument_count = 0},
            {.name = "host_self_trap", .argument_count = 0},
            {},
            {.name = "mach_msg_trap", .argument_count = 7},
            {.name = "mach_msg_overwrite_trap", .argument_count = 8},
            {.name = "semaphore_signal_trap", .argument_count = 1},
            {.name = "semaphore_signal_all_trap", .argument_count = 1},
            {.name = "semaphore_signal_thread_trap", .argument_count = 2},
            {.name = "semaphore_wait_trap", .argument_count = 1},
            {.name = "semaphore_wait_signal_trap", .argument_count = 2},
            {.name = "semaphore_timedwait_trap", .argument_count = 3},
            {.name = "semaphore_timedwait_signal_trap", .argument_count = 4},
            {.name = "_kernelrpc_mach_port_get_attributes_trap", .argument_count = 5},
            {.name = "_kernelrpc_mach_port_guard_trap", .argument_count = 4},
            {.name = "_kernelrpc_mach_port_unguard_trap", .argument_count = 3},
            {.name = "mach_generate_activity_id", .argument_count = 3},
            {.name = "task_name_for_pid", .argument_count = 3},
            {.name = "task_for_pid", .argument_count = 3},
            {.name = "pid_for_task", .argument_count = 2},
            {.name = "mach_msg2_trap", .argument_count = 8},
            {.name = "macx_swapon", .argument_count = 4},
            {.name = "macx_swapoff", .argument_count = 2},
            {.name = "thread_get_special_reply_port", .argument_count = 0},
            {.name = "macx_triggers", .argument_count = 4},
            {.name = "macx_backing_store_suspend", .argument_count = 1},
            {.name = "macx_backing_store_recovery", .argument_count = 1},
            {},
            {},
            {},
            {},
            {.name = "pfz_exit", .argument_count = 0},
            {.name = "swtch_pri", .argument_count = 0},
            {.name = "swtch", .argument_count = 0},
            {.name = "thread_switch", .argument_count = 3},
            {.name = "clock_sleep_trap", .argument_count = 5},
            {.name = "mach_vm_reclaim_update_kernel_accounting_trap", .argument_count = 3},
            {},
            {},
            {},
            {},
            {},
            {},
            {.name = "host_create_mach_voucher_trap", .argument_count = 4},
            {},
            {.name = "mach_voucher_extract_attr_recipe_trap", .argument_count = 4},
            {},
            {},
            {},
            {.name = "_kernelrpc_mach_port_type_trap", .argument_count = 3},
            {.name = "_kernelrpc_mach_port_request_notification_trap", .argument_count = 7},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {.name = "_exclaves_ctl_trap", .argument_count = 8},
            {.name = "mach_timebase_info_trap", .argument_count = 1},
            {.name = "mach_wait_until_trap", .argument_count = 1},
            {.name = "mk_timer_create_trap", .argument_count = 0},
            {.name = "mk_timer_destroy_trap", .argument_count = 1},
            {.name = "mk_timer_arm_trap", .argument_count = 2},
            {.name = "mk_timer_cancel_trap", .argument_count = 2},
            {.name = "mk_timer_arm_leeway_trap", .argument_count = 4},
            {.name = "debug_control_port_for_pid", .argument_count = 3},
            {},
            {},
            {},
            {.name = "iokit_user_client_trap", .argument_count = 8},
        }};
    }

    const std::string_view MACH_TRAP_TABLE_XNU_VERSION = "xnu-12377.121.6";

    size_t mach_trap_table_size()
    {
        return traps.size();
    }

    const mach_trap_prototype* find_mach_trap_prototype(const uint32_t index)
    {
        if (index >= traps.size() || traps[index].name.empty())
        {
            return nullptr;
        }

        return &traps[index];
    }
}
