#!/usr/bin/env python3
"""Generates sogen's BSD syscall and Mach trap prototype tables from vendored XNU sources.

Run by hand after src/tools/gen-bsd-syscall-table/fetch.sh; CI re-runs it and diffs the result.
"""

import argparse
import json
import pathlib
import re
import sys

ENTRY_RE = re.compile(r"^(\d+)\s+\S+\s+\S+\s+\{(.*?)\}")
PROTO_RE = re.compile(r"^(?P<head>.+?)\((?P<args>.*)\)\s*(?P<attrs>[A-Za-z0-9_ ]*);?\s*$")
MACH_TRAP_RE = re.compile(r"/\*\s*(\d+)\s*\*/\s*MACH_TRAP\(\s*([A-Za-z_]\w*)\s*,\s*(\d+)")
IDENTIFIER_RE = re.compile(r"[A-Za-z_]\w*$")

SKIP_NAMES = {"nosys", "enosys"}


def split_head(head):
    head = head.strip()
    match = IDENTIFIER_RE.search(head)
    if match is None:
        raise ValueError("no syscall name in '%s'" % head)
    name = match.group(0)
    # XNU spells 33 entries "sys_close", "sys_fcntl" and so on to keep the table from colliding with its
    # own kernel functions; makesyscalls.sh strips the prefix when it writes sys/syscall.h, and userspace
    # only ever knows the stripped name. Verified against this host's SDK header for every one of them.
    if name.startswith("sys_") and len(name) > 4:
        name = name[4:]
    return head[: match.start()].strip(), name


def split_argument(text, index):
    text = text.strip()
    if not text or text == "void":
        return None
    if text == "...":
        return None
    match = IDENTIFIER_RE.search(text)
    if match is None or match.start() == 0:
        return (text, "arg%d" % index)
    name = match.group(0)
    type_text = text[: match.start()].strip()
    if not type_text:
        return (text, "arg%d" % index)
    return (re.sub(r"\s+", " ", type_text), name)


def parse_syscalls_master(path):
    entries = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "/*", ";", "*")):
            continue
        match = ENTRY_RE.match(stripped)
        if match is None:
            continue
        number = int(match.group(1))
        body = match.group(2).strip()
        if not body:
            continue
        proto = PROTO_RE.match(body)
        if proto is None:
            continue
        try:
            return_type, name = split_head(proto.group("head"))
        except ValueError:
            continue
        if name in SKIP_NAMES:
            continue
        arguments = []
        for index, piece in enumerate(proto.group("args").split(",")):
            argument = split_argument(piece, index)
            if argument is not None:
                arguments.append(argument)
        if len(arguments) > 8:
            raise SystemExit("syscall %d (%s) declares %d arguments; arm64 allows 8" % (number, name, len(arguments)))
        if number in entries:
            continue
        entries[number] = (name, return_type or "int", arguments)
    if not entries:
        raise SystemExit("no syscall entries parsed; the vendored syscalls.master is not in the expected format")

    # Slot 0 is spelled "nosys" in the table and carries the comment "{ indirect syscall }": the real
    # number arrives in x0 and the arguments shift by one. Every other nosys really is an unused slot, so
    # the skip stays and this one entry is named the way the ABI and the SDK header name it.
    entries.setdefault(0, ("syscall", "int", [("int", "number")]))
    return entries


def parse_syscall_sw(path):
    # arm64 XNU dispatches these two in handle_svc before it reaches the generic trap table, so they are
    # absent from syscall_sw.c. setdefault keeps a real table entry from silently replacing the seed.
    entries = {3: ("mach_absolute_time", 0), 4: ("mach_continuous_time", 0)}
    for match in MACH_TRAP_RE.finditer(path.read_text(encoding="utf-8", errors="replace")):
        index = int(match.group(1))
        name = match.group(2)
        count = int(match.group(3))
        if name in ("kern_invalid", "_kernelrpc_mach_port_placeholder"):
            continue
        entries.setdefault(index, (name, count))
    if not entries:
        raise SystemExit("no MACH_TRAP entries parsed; the vendored syscall_sw.c is not in the expected format")
    return entries


def cstring(text):
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def emit_bsd(entries, provenance, output):
    size = max(entries) + 1
    lines = []
    lines.append("// clang-format off")
    lines.append("// Generated by src/tools/gen-bsd-syscall-table/gen_bsd_syscall_table.py. Do not edit.")
    lines.append("// Source: apple-oss-distributions/xnu %s bsd/kern/syscalls.master" % provenance["xnu_version"])
    lines.append('#include "bsd_syscall_table.hpp"')
    lines.append("")
    lines.append("#include <array>")
    lines.append("")
    lines.append("namespace sogen")
    lines.append("{")
    lines.append("    namespace")
    lines.append("    {")
    for number in sorted(entries):
        _, _, arguments = entries[number]
        if not arguments:
            continue
        lines.append("        constexpr std::array<bsd_syscall_argument, %d> args_%d{{" % (len(arguments), number))
        for type_text, name in arguments:
            lines.append("            {.type = %s, .name = %s}," % (cstring(type_text), cstring(name)))
        lines.append("        }};")
    lines.append("")
    lines.append("        constexpr std::array<bsd_syscall_prototype, %d> prototypes{{" % size)
    for number in range(size):
        entry = entries.get(number)
        if entry is None:
            lines.append("            {},")
            continue
        name, return_type, arguments = entry
        span = "args_%d" % number if arguments else "{}"
        lines.append("            {.name = %s, .return_type = %s, .arguments = %s}," % (cstring(name), cstring(return_type), span))
    lines.append("        }};")
    lines.append("    }")
    lines.append("")
    lines.append("    const std::string_view BSD_SYSCALL_TABLE_XNU_VERSION = %s;" % cstring(provenance["xnu_version"]))
    lines.append(
        "    const std::string_view BSD_SYSCALL_TABLE_SOURCE_SHA256 = %s;"
        % cstring(provenance["files"]["syscalls.master"]["sha256"])
    )
    lines.append("")
    lines.append("    size_t bsd_syscall_table_size()")
    lines.append("    {")
    lines.append("        return prototypes.size();")
    lines.append("    }")
    lines.append("")
    lines.append("    const bsd_syscall_prototype* find_bsd_syscall_prototype(const uint32_t number)")
    lines.append("    {")
    lines.append("        if (number >= prototypes.size() || prototypes[number].name.empty())")
    lines.append("        {")
    lines.append("            return nullptr;")
    lines.append("        }")
    lines.append("")
    lines.append("        return &prototypes[number];")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")


def emit_mach(entries, provenance, output):
    size = max(entries) + 1
    lines = []
    lines.append("// clang-format off")
    lines.append("// Generated by src/tools/gen-bsd-syscall-table/gen_bsd_syscall_table.py. Do not edit.")
    lines.append("// Source: apple-oss-distributions/xnu %s osfmk/kern/syscall_sw.c" % provenance["xnu_version"])
    lines.append('#include "mach_trap_table.hpp"')
    lines.append("")
    lines.append("#include <array>")
    lines.append("")
    lines.append("namespace sogen")
    lines.append("{")
    lines.append("    namespace")
    lines.append("    {")
    lines.append("        constexpr std::array<mach_trap_prototype, %d> traps{{" % size)
    for index in range(size):
        entry = entries.get(index)
        if entry is None:
            lines.append("            {},")
            continue
        name, count = entry
        lines.append("            {.name = %s, .argument_count = %d}," % (cstring(name), count))
    lines.append("        }};")
    lines.append("    }")
    lines.append("")
    lines.append("    const std::string_view MACH_TRAP_TABLE_XNU_VERSION = %s;" % cstring(provenance["xnu_version"]))
    lines.append("")
    lines.append("    size_t mach_trap_table_size()")
    lines.append("    {")
    lines.append("        return traps.size();")
    lines.append("    }")
    lines.append("")
    lines.append("    const mach_trap_prototype* find_mach_trap_prototype(const uint32_t index)")
    lines.append("    {")
    lines.append("        if (index >= traps.size() || traps[index].name.empty())")
    lines.append("        {")
    lines.append("            return nullptr;")
    lines.append("        }")
    lines.append("")
    lines.append("        return &traps[index];")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")


def main():
    root = pathlib.Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--vendor", type=pathlib.Path, default=root / "vendor")
    parser.add_argument(
        "--bsd-output",
        type=pathlib.Path,
        default=root / ".." / ".." / "macos-emulator" / "trace" / "bsd_syscall_table.generated.cpp",
    )
    parser.add_argument(
        "--mach-output",
        type=pathlib.Path,
        default=root / ".." / ".." / "macos-emulator" / "trace" / "mach_trap_table.generated.cpp",
    )
    options = parser.parse_args()

    provenance = json.loads((options.vendor / "provenance.json").read_text(encoding="utf-8"))

    emit_bsd(parse_syscalls_master(options.vendor / "syscalls.master"), provenance, options.bsd_output.resolve())
    emit_mach(parse_syscall_sw(options.vendor / "syscall_sw.c"), provenance, options.mach_output.resolve())
    return 0


if __name__ == "__main__":
    sys.exit(main())
