include(ExternalProject)
include(ProcessorCount)

find_package(Perl REQUIRED)
find_package(Threads REQUIRED)

set(OPENSSL_SOURCE_DIR "${PROJECT_SOURCE_DIR}/deps/openssl")
set(OPENSSL_BUILD_DIR "${CMAKE_BINARY_DIR}/deps/openssl-build")
set(OPENSSL_INSTALL_DIR "${CMAKE_BINARY_DIR}/deps/openssl-install")

file(MAKE_DIRECTORY "${OPENSSL_INSTALL_DIR}/include")

set(OPENSSL_CONFIGURE_ARGS
  no-shared
  no-apps
  no-tests
  no-module
  "--prefix=${OPENSSL_INSTALL_DIR}"
  "--openssldir=${OPENSSL_INSTALL_DIR}/ssl"
)
set(OPENSSL_CONFIGURE_COMMAND "${PERL_EXECUTABLE}" "${OPENSSL_SOURCE_DIR}/Configure")
set(OPENSSL_CONFIGURE_ENV)

if(WIN32 AND NOT MINGW)
  if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64)$")
      set(OPENSSL_TARGET VC-WIN64-ARM)
    else()
      set(OPENSSL_TARGET VC-WIN64A)
    endif()
  else()
    set(OPENSSL_TARGET VC-WIN32)
  endif()

  find_program(OPENSSL_MAKE_PROGRAM nmake REQUIRED)
  list(APPEND OPENSSL_CONFIGURE_ARGS "${OPENSSL_TARGET}")
  set(OPENSSL_BUILD_COMMAND "${OPENSSL_MAKE_PROGRAM}")
  set(OPENSSL_INSTALL_COMMAND "${OPENSSL_MAKE_PROGRAM}" install_sw)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libssl.lib")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libcrypto.lib")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
  if(CMAKE_ANDROID_ARCH_ABI STREQUAL "arm64-v8a")
    set(OPENSSL_TARGET android-arm64)
  elseif(CMAKE_ANDROID_ARCH_ABI STREQUAL "armeabi-v7a")
    set(OPENSSL_TARGET android-arm)
  elseif(CMAKE_ANDROID_ARCH_ABI STREQUAL "x86_64")
    set(OPENSSL_TARGET android-x86_64)
  elseif(CMAKE_ANDROID_ARCH_ABI STREQUAL "x86")
    set(OPENSSL_TARGET android-x86)
  else()
    message(FATAL_ERROR "Unsupported Android ABI for OpenSSL: ${CMAKE_ANDROID_ARCH_ABI}")
  endif()

  if(NOT CMAKE_ANDROID_NDK)
    message(FATAL_ERROR "CMAKE_ANDROID_NDK must be set to build OpenSSL for Android")
  endif()

  list(APPEND OPENSSL_CONFIGURE_ARGS "${OPENSSL_TARGET}")
  get_filename_component(OPENSSL_ANDROID_TOOLCHAIN_BIN "${CMAKE_C_COMPILER}" DIRECTORY)
  list(APPEND OPENSSL_CONFIGURE_ENV
    "ANDROID_NDK_ROOT=${CMAKE_ANDROID_NDK}"
    --modify "PATH=path_list_prepend:${OPENSSL_ANDROID_TOOLCHAIN_BIN}")
  find_program(OPENSSL_MAKE_PROGRAM NAMES gmake make REQUIRED)
  set(OPENSSL_BUILD_COMMAND "${OPENSSL_MAKE_PROGRAM}" -j)
  set(OPENSSL_INSTALL_COMMAND "${OPENSSL_MAKE_PROGRAM}" install_sw)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libssl.a")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libcrypto.a")
elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
  if(CMAKE_OSX_SYSROOT MATCHES "[Ii]phone[Ss]imulator")
    if(CMAKE_OSX_ARCHITECTURES MATCHES "arm64")
      set(OPENSSL_TARGET iossimulator-arm64-xcrun)
    else()
      set(OPENSSL_TARGET iossimulator-x86_64-xcrun)
    endif()
  elseif(CMAKE_OSX_ARCHITECTURES MATCHES "arm64")
    set(OPENSSL_TARGET ios64-xcrun)
  else()
    message(FATAL_ERROR "Unsupported iOS architecture for OpenSSL: ${CMAKE_OSX_ARCHITECTURES}")
  endif()

  list(APPEND OPENSSL_CONFIGURE_ARGS "${OPENSSL_TARGET}")
  find_program(OPENSSL_MAKE_PROGRAM NAMES gmake make REQUIRED)
  set(OPENSSL_BUILD_COMMAND "${OPENSSL_MAKE_PROGRAM}" -j)
  set(OPENSSL_INSTALL_COMMAND "${OPENSSL_MAKE_PROGRAM}" install_sw)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libssl.a")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libcrypto.a")
elseif(EMSCRIPTEN)
  list(APPEND OPENSSL_CONFIGURE_ARGS linux-generic64)
  find_program(OPENSSL_MAKE_PROGRAM NAMES gmake make REQUIRED)
  set(OPENSSL_BUILD_COMMAND "${OPENSSL_MAKE_PROGRAM}" -j)
  set(OPENSSL_INSTALL_COMMAND "${OPENSSL_MAKE_PROGRAM}" install_sw)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libssl.a")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libcrypto.a")
elseif(MINGW)
  if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(OPENSSL_TARGET mingw64)
  else()
    set(OPENSSL_TARGET mingw)
  endif()
  list(APPEND OPENSSL_CONFIGURE_ARGS "${OPENSSL_TARGET}")
  find_program(OPENSSL_MAKE_PROGRAM NAMES gmake make REQUIRED)
  set(OPENSSL_BUILD_COMMAND "${OPENSSL_MAKE_PROGRAM}" -j)
  set(OPENSSL_INSTALL_COMMAND "${OPENSSL_MAKE_PROGRAM}" install_sw)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libssl.a")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libcrypto.a")
else()
  find_program(OPENSSL_MAKE_PROGRAM NAMES gmake make REQUIRED)
  set(OPENSSL_BUILD_COMMAND "${OPENSSL_MAKE_PROGRAM}" -j)
  set(OPENSSL_INSTALL_COMMAND "${OPENSSL_MAKE_PROGRAM}" install_sw)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libssl.a")
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_INSTALL_DIR}/lib/libcrypto.a")
endif()

if(NOT CMAKE_SYSTEM_NAME STREQUAL "Android" AND NOT CMAKE_SYSTEM_NAME STREQUAL "iOS")
  list(APPEND OPENSSL_CONFIGURE_ENV "CC=${CMAKE_C_COMPILER}")
endif()
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Android")
  list(APPEND OPENSSL_CONFIGURE_ENV "AR=${CMAKE_AR}" "RANLIB=${CMAKE_RANLIB}")
endif()

ProcessorCount(OPENSSL_BUILD_JOBS)
if(OPENSSL_BUILD_JOBS GREATER 0 AND NOT WIN32)
  list(APPEND OPENSSL_BUILD_COMMAND "${OPENSSL_BUILD_JOBS}")
endif()

ExternalProject_Add(openssl-build
  SOURCE_DIR "${OPENSSL_SOURCE_DIR}"
  BINARY_DIR "${OPENSSL_BUILD_DIR}"
  DOWNLOAD_COMMAND ""
  UPDATE_COMMAND ""
  CONFIGURE_COMMAND "${CMAKE_COMMAND}" -E env ${OPENSSL_CONFIGURE_ENV}
    ${OPENSSL_CONFIGURE_COMMAND} ${OPENSSL_CONFIGURE_ARGS}
  BUILD_COMMAND ${OPENSSL_BUILD_COMMAND}
  INSTALL_COMMAND ${OPENSSL_INSTALL_COMMAND}
  BUILD_BYPRODUCTS "${OPENSSL_SSL_LIBRARY}" "${OPENSSL_CRYPTO_LIBRARY}"
)

add_library(OpenSSL::Crypto STATIC IMPORTED GLOBAL)
set_target_properties(OpenSSL::Crypto PROPERTIES
  IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
  INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INSTALL_DIR}/include"
  INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS};Threads::Threads"
)

add_library(OpenSSL::SSL STATIC IMPORTED GLOBAL)
set_target_properties(OpenSSL::SSL PROPERTIES
  IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
  INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INSTALL_DIR}/include"
  INTERFACE_LINK_LIBRARIES OpenSSL::Crypto
)

if(WIN32)
  set_property(TARGET OpenSSL::Crypto APPEND PROPERTY INTERFACE_LINK_LIBRARIES
    "ws2_32;crypt32;advapi32;user32")
endif()
