name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        include:
          - configuration: Debug
            preset: debug
          - configuration: Release
            preset: release
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: CMake Build
        run: cmake --workflow --preset=${{matrix.preset}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows ${{matrix.configuration}} Artifacts
          path: |
            build/${{matrix.preset}}/artifacts/emulator.exe
            build/${{matrix.preset}}/artifacts/emulator.pdb
